### ISSUE TITLE
Allow 'SpatVector' input

### ISSUE THREAD

**Issue by AMBarbosa** [riatelab/mapiso#1]
Hi! Kudos for implementing 'SpatRaster' input from 'terra' , but could you implement also 'SpatVector'? 'sf' is not the only modern (and increasingly used) vector format out there ;)  Cheers

**Comment by rCarto** [comment]
Done! 
But please note that you'll still have to `terra::vect()` the resulting contour polygons.

**Comment by AMBarbosa** [comment]
Cool, thanks! I'd suggest (but feel free to ignore!) outputting SpatVector if the input was SpatVector, with something like this before `return(iso)`:
```
if (inherits(x = x, what = "SpatVector")) iso <- terra::vect(iso)
```
(I don't mean to sound picky, but for teaching, it can be confusing for students to have to convert between spatial formats, so I like to avoid it whenever possible)
